from .commands_cfg import ObjectGoalPosCommandCfg, EEGoalPosCommandCfg, DynamicObjectGoalPosCommandCfg
from .position_command import ObjectGoalPosCommand, EEGoalPosCommand, DynamicObjectGoalPosCommand